// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqhmiuZzjulum3p465v4GsvFuW0febyZE',
    appId: '1:62088129575:web:12fc991646e99acb75f202',
    messagingSenderId: '62088129575',
    projectId: 'my-e-commercial-app-5b8ef',
    authDomain: 'my-e-commercial-app-5b8ef.firebaseapp.com',
    storageBucket: 'my-e-commercial-app-5b8ef.appspot.com',
    measurementId: 'G-0T743XDH9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTtD0i7mDCXJFgZENYyMyCb60GTBtBHw',
    appId: '1:62088129575:android:bba51daa0245f52275f202',
    messagingSenderId: '62088129575',
    projectId: 'my-e-commercial-app-5b8ef',
    storageBucket: 'my-e-commercial-app-5b8ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZTPOixUOqKDuUozdLQuYT3mOrC0GBmb8',
    appId: '1:62088129575:ios:d10d4d2c592b5a8675f202',
    messagingSenderId: '62088129575',
    projectId: 'my-e-commercial-app-5b8ef',
    storageBucket: 'my-e-commercial-app-5b8ef.appspot.com',
    iosClientId: '62088129575-7saqb75qe8lnejldmmvsd0hri0v704op.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZTPOixUOqKDuUozdLQuYT3mOrC0GBmb8',
    appId: '1:62088129575:ios:d10d4d2c592b5a8675f202',
    messagingSenderId: '62088129575',
    projectId: 'my-e-commercial-app-5b8ef',
    storageBucket: 'my-e-commercial-app-5b8ef.appspot.com',
    iosClientId: '62088129575-7saqb75qe8lnejldmmvsd0hri0v704op.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceapp',
  );
}
